name: Rust

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    # Only cache cargo registry (dependencies), not target directory
    # Target caching conflicts with nix environment and multiple build targets
    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-
    
    - name: Check formatting
      run: nix develop -c cargo fmt --check
    
    - name: Run linting
      run: nix develop -c cargo clippy --all-targets -- -D warnings
    
    - name: Build
      run: nix develop -c cargo build
    
    - name: Run tests
      run: nix develop -c cargo test
    
    - name: Run integration tests
      run: |
        echo "Running integration tests with automatic relay setup..."
        nix develop -c cargo run --bin gitsmith-integration-tests -- all
    
    - name: Build with nix (static musl binary)
      run: nix build
    
    - name: Verify static binary
      run: |
        echo "Checking if the binary is statically linked..."
        file ./result/bin/gitsmith | grep -E "(statically linked|static-pie linked)" || (echo "Binary is not static!" && exit 1)
        echo "✓ Binary is properly static linked"